### ISSUE TITLE
Mod suggestion: ArchitectureCraft

### ISSUE THREAD

**Issue by Sandstroem** [MyM-ModpackTeam/Eternal-Skies#6]
https://mods.curse.com/mc-mods/minecraft/242001-architecturecraft

A pretty cool mod that allows to cut blocks into certain shapes. I played a bit on Beyond with it, for example I used round pillars in my blood altar (made out of crafting tables to troll Sico)

https://i.imgur.com/mvL3FVD.png

**Comment by Aiidoneus** [comment]
Added
